### ISSUE TITLE
Validate user input

### ISSUE THREAD

**Issue by zppratt** [zppratt/visualtracert#1]
We need to somehow check that the data being sent to the server is being validated.

**Comment by zppratt** [comment]
@SunnyDjinn What kind of validation do we want? I see you already have 0-255 covered for each

**Comment by SunnyDjinn** [comment]
I thought we could change the 4 fields into only 1, or make it faster to type  (auto tab maybe?). And we need to send only 1 object instead of 4 fields, so we need to preprocess it anyway
