### ISSUE TITLE
Solve problem of permission to create raw sockets in tracerouteimpl.php

### ISSUE THREAD

**Issue by SunnyDjinn** [zppratt/visualtracert#18]
Right now the traceroute should work but the server cannot create raw sockets (needs to be root). We need to fix this ASAP. Once this works, the server side is almost done

**Comment by zppratt** [comment]
http://www.adayinthelifeof.nl/2010/07/30/creating-a-traceroute-program-in-php/

"This means it probably is not going to work when running it from a web-server"

Hmm...

**Comment by zppratt** [comment]
It's really looking like we will probably need to standardize this to linux and use the exec call again unfortunately.

**Comment by SunnyDjinn** [comment]
I would rather modify it to work with UDP sockets instead, the exec is just
a pain and goes against our asynchronous behavior.

EDIT: stupid email that adds the signature automatically...

**Comment by SunnyDjinn** [comment]
How about we just give root access to our server? Does is matter if we need to run it as root? I understand that for a company it would be a problem, but do we want to sell the product to a company or... ?
